### ISSUE TITLE
undefined method `empty?' for nil:NilClass at capybara_methods_proxy.rb:23:in `within_frame?'

### ISSUE THREAD

**Issue by yurygnutov** [strongqa/howitzer#221]
Hi,

after upgrade Howitzer from `2.0.1` to `2.0.2` we experience issues when some tests executes one after another.

```
page.open
NoMethodError: undefined method `empty?' for nil:NilClass
from /Users/***/.rvm/gems/ruby-2.3.3@***gems/howitzer-2.0.2/lib/howitzer/web/capybara_methods_proxy.rb:23:in `within_frame?'`
```

after downgrade back to `2.0.1` issue disappears.

Thanks

**Comment by romikoops** [comment]
It is related with activesupport gem somehow. I will investigate and let you know about results today

**Comment by romikoops** [comment]
@yurygnutov  Please test my fix. Update your Gemfile like that

```ruby
gem 'howitzer', git: 'https://github.com/strongqa/howitzer.git', branch: 'fix_issue_221'
```

and then:

```
bundle update howitzer
```

**Comment by yurygnutov** [comment]
@romikoops fix solves the issue. Thanks

**Comment by romikoops** [comment]
Merged fixes to **master**. Hopefully capybara contributors will fix issue with frame https://github.com/teamcapybara/capybara/issues/1845 and we will remove this hell monkey patch.
