### ISSUE TITLE
Howitzer::CommunicationError: key not found: :ciphers

### ISSUE THREAD

**Issue by knlynda** [strongqa/howitzer#223]
Method `Howitzer::MailgunApi::Client#get` failed on ruby `2.4.0` due to rest-client bug https://github.com/rest-client/rest-client/issues/600.

**Comment by Lec1k** [comment]
Couldn't reproduce it on my environment, but this bug is fixed in [rest-client(2.0.1)](/rest-client/rest-client/pull/573)

**Comment by romikoops** [comment]
Looks like it was fixed in rest-client.
