### ISSUE TITLE
selenium // Chrome// During test running window was opened not in maximum

### ISSUE THREAD

**Issue by hardness** [strongqa/howitzer#231]
## Meta
Howitzer Version: 2.0.3

Driver and browser information: selenium-webdriver (3.4.2),  Chrome 59 

Gem Versions:

## Expected Behavior
with 'maximum - yes' function window should be opened in maximum
## Actual Behavior
window was opened not for maximum

**Comment by Lec1k** [comment]
Seems this issue is only reproducible on Mac. This bug is already tracked on [chromium support](https://bugs.chromium.org/p/chromedriver/issues/detail?id=985). You can use some workarounds from the linked thread.

**Comment by romikoops** [comment]
In master
