### ISSUE TITLE
Method `set` on the element doesn't actually set but adds value

### ISSUE THREAD

**Issue by kirpichenko** [strongqa/howitzer#240]
Expected behaviour
element should contain provided value 

Actual behaviour
element concatenates current and  provided values

Example
You have `field` element with `value` pre filled. After setting to `new_value` it contains `valuenew_value` instead of `new_value`

**Comment by romikoops** [comment]
@kirpichenko it is not a Howitzer issue. Looks like It is selenium google chrome headless issue.
For more details and workarounds please follow this issue https://github.com/erikras/redux-form/issues/686
