### ISSUE TITLE
Providing a means to catch duplicate page objects

### ISSUE THREAD

**Issue by jasonmci** [strongqa/howitzer#241]
## Meta
It is easy for testers to add redundant page elements, that is, adding another element for an element that already exists. These elements may have different names. 

It would be good to provide a linting tool, or at least provide a means to write tests to verify unique page elements. This can be done by checking the paths Capybara returns. 

It may also be a logical next step to sort all the page elements of where they appear in the DOM

Suggest a method to at least get the path back with a 

`show_username_element_path`  

method which could then be used to compare paths of elements on the page. 

Capybara returns a path that looks like this: 

`"/html/body/div/div/form/fieldset[1]/div/div/input"`  which will be unique within the DOM

**Comment by romikoops** [comment]
connected issue #264
