### ISSUE TITLE
Trying to use BrowserStack keeps trying to load chromedriver

### ISSUE THREAD

**Issue by rchady** [strongqa/howitzer#251]
## Meta
Howitzer Version:

Driver and browser information:

Gem Versions:

## Expected Behavior
Configured howitzer to use browserstack and I expect it to connect there and run the tests there.

## Actual Behavior
I get an error that it can't find chromedriver.

## Steps to reproduce
1. BRAND NEW install of howitzer
2. Update config/default.yml so driver is set to browserstack
3) Write a trivial web/page/homepage.rb and spec/homepage_spec.rb
4) Run 'rake'

**Comment by Lec1k** [comment]
Hi @rchady ,
Can you specify which version of howitzer do you use and provide link to your example.
I couldn't reproduce this issue:
1. deleted chromedriver
2. switched to browserstack
Everything worked as intended.
My assumption is that you use older version of howitzer and configs for all drivers are located in one file capybara.rb, you can comment out all drivers except browsertack, should help in your case

**Comment by Lec1k** [comment]
Also check if you have custom.yml in your config folder, custom.yml overrides setting in default.yml. If you not using it, you can simply delete custom.yml from your config folder. More detailed infromation [here](https://github.com/romikoops/sexy_settings)

**Comment by rchady** [comment]
Aha, that makes sense.  Just as a clarification, this is a brand new install from 'gem install howitzer'.  It appears it ships with a custom.yml in place.  When I was reading through the initial getting started document I did not see a reference to custom.yml so I missed that it existed.

Might I suggest moving custom.yml in the gem to custom.yml.example?

**Comment by romikoops** [comment]
@rchady It was designed like that. 
config/default.yml - is file under Git and for CI usage only (defaults)
config/custom.yml - is file EXCLUDED from Git and for local usage only (it prevents affecting build on CI and allows you to override any setting from default.yml)
We will extend the documentation with it

**Comment by rchady** [comment]
@romikoops, I understand it was meant to allow overriding.  What I meant was you might not want to ship the custom.yml "live" in the gem.  The normal way is to leave it as custom.yml.example and then put a comment in it and/or put it in the documentation.

Anyhow, thank you for the quick response.  I'm slowly working through this from a fresh gem install and trying to see if it'll work for my needs.  I appreciate all the work you have done.
