### ISSUE TITLE
Log files are created in top project folder for failed scenarios

### ISSUE THREAD

**Issue by mikhaillopandia** [strongqa/howitzer#252]
## Meta
Howitzer Version: 2.1.0
Driver and browser information: selenium 3.7 ChromeDriver 2.33 Chrome 62

## Expected Behavior
Log files are always created in /log folder
## Actual Behavior
If there is an error occurred, .png and .html prove files are created in the root project folder
## Steps to reproduce

1. Install Howitzer v2.1.0
2. Create new project or update old one with new gem 
3. Make at least one Scenario fails
4. Set following settings in default.yml:
    driver: selenium
    selenium_browser: chrome
5. Run test with "rake features" 
6. See that logs have been created in your root project folder

As far as I understand, 
https://github.com/strongqa/howitzer/blob/b7e606ad8f97535b3210062df408f38da3940217/generators/config/templates/drivers/headless_chrome.rb#L13
should be applied for for all drivers in capybara.rb, but not only for headless_chrome and phantomjs.

**Comment by Lec1k** [comment]
In master 0214a0bbe29118f91f8ba1f67b313c21b2e7ed22
