### ISSUE TITLE
Browserstack screenshots?

### ISSUE THREAD

**Issue by rchady** [strongqa/howitzer#254]
## Meta
Howitzer Version:

Driver and browser information:

Gem Versions:

## Expected Behavior
A screenshot will be taken on error on browserstack.

## Actual Behavior
I get the following error:

```
capybara-screenshot could not detect a screenshot driver for 'browserstack'. Saving with default with unknown results.
WARN: Screenshot could not be saved. An exception is raised: #<NoMethodError: undefined method `render' for #<Capybara::Selenium::Driver:0x007f8c7e2ca238>>.
2017/11/22 08:57:31 [INFO] :: CLOUD VIDEO [0m 0s] - [0m 30s] URL: [NOT IMPLEMENTED]
```
## Steps to reproduce

1) Write a failing test using the browserstack driver.
2) Run rake
3) Watch it fail.

It is very possible I'm missing something, but I gripped everything looking for any combination of 'browserstack' and 'screenshot'.  Is there support yet?  If not, how can I tell it to not try to take one?

**Comment by Lec1k** [comment]
Append 
```
Capybara::Screenshot.register_driver(:browserstack) do |driver, path|
  driver.browser.save_screenshot path
end
```
to your browserstack driver config in config/drivers/browserstack.rb

**Comment by Lec1k** [comment]
In master d7e806d7a3f710036648c5cd4b4ef996c1782b3e
