### ISSUE TITLE
config.disable_monkey_patching! for Rspec project

### ISSUE THREAD

**Issue by mikhaillopandia** [strongqa/howitzer#256]
## Meta
Howitzer Version: 2.1.0
Driver and browser information: selenium 3.7 ChromeDriver 2.33 Chrome 62

## Description

https://github.com/strongqa/howitzer/blob/417dfdad85df5168d35d430b61698e015b8c868b/generators/rspec/templates/spec_helper.rb#L15

config.disable_monkey_patching! besides `disable_monkey_patching = true` sets
`expose_dsl_globally = false` as well: https://github.com/rspec/rspec-core/blob/94bceebb79357ab42f37ae76a3ab057d4c529b94/lib/rspec/core/configuration.rb#L1726
As a result we have to write 'RSpec.' before each rspec 'feature' or 'context' or 'describe'

## Expected Behavior
Tests are carried out
## Actual Behavior
```
An error occurred while loading ./spec/acceptance/login_spec.rb.
Failure/Error:
  feature 'Log In', smoke: true do
    scenario 'user can open login page via menu' do
      HomePage.open
      HomePage.on { main_menu_section.choose_menu('Log In') }
      expect(LoginPage).to be_displayed
    end
  end

NoMethodError:
  undefined method `feature' for main:Object
# ./spec/acceptance/login_spec.rb:3:in `<top (required)>'
No examples found.
```

## Steps to reproduce
1. Create new project with `howitzer new <PROJECT NAME> --rspec`
2. Create '%spec.rb' file
3. Run `rake features`

**Comment by romikoops** [comment]
It is good to have this issue here, because it can be useful for howitzer users.

Actually, we had the methods in global scope before Rspec did not introduce the options. It happened somewhere in Rspec 3 as far as I remember. Just see what is going when we define methods in global context:

```
2.4.1 :001 > def foo
2.4.1 :002?>   1
2.4.1 :003?>   end
 => :foo 
2.4.1 :004 > class Bar
2.4.1 :005?>   end
 => nil 
2.4.1 :006 > Bar.new.foo
 => 1 
```

Of course it is not good. So, having module based methods resolves the issue:

```
[1] pry(main)> module Baz
[1] pry(main)*   def self.foo
[1] pry(main)*     1
[1] pry(main)*   end  
[1] pry(main)* end  
=> :foo
[2] pry(main)> Baz.foo
=> 1
[3] pry(main)> class Bar
[3] pry(main)* end  
=> nil
[4] pry(main)> Bar.new.foo
NoMethodError: undefined method `foo' for #<Bar:0x007f96d2155160>
```

So, @mikhaillopandia please replace `feature` with `RSpec.feature` in your tests.
