### ISSUE TITLE
Support Zalenium

### ISSUE THREAD

**Issue by romikoops** [strongqa/howitzer#269]
https://github.com/zalando/zalenium

**Comment by Lec1k** [comment]
Using [Zalenium](https://github.com/zalando/zalenium) with Howitzer:
1. Generate Howitzer project
2. Install docker
3. Pull docker-selenium

    ```docker pull elgalu/selenium```

4. Pull Zalenium

    ```docker pull dosel/zalenium```

5. Run Zalenium

``` docker run --rm -ti --name zalenium -p 4444:4444 \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /tmp/videos:/home/seluser/videos \
    --privileged dosel/zalenium start
```
6. Set Howitzer **driver** in default.yml to **selenium_grid**
7. Set **selenium_hub_url** in default.yml to `"http://127.0.0.1:4444/wd/hub"`

**Comment by esthinri** [comment]
docker run -v /var/run/docker.sock:/var/run/docker.sock \
    -v /tmp/videos:/home/seluser/videos \
    --privileged dosel/zalenium start ?

**Comment by Lec1k** [comment]
Made a typo, corrected command for running Zalenium.

**Comment by esthinri** [comment]
i try command "cucumber" for run tests but not work.
