### ISSUE TITLE
Support Gherkin in Portuguese

### ISSUE THREAD

**Issue by esthinri** [strongqa/howitzer#271]
## Meta
Howitzer Version:2.1.1
Driver and browser information: selenium_grid
Gem Versions: 2.5.1

Its possible i work usign gherkin in portuguese?

**Comment by romikoops** [comment]
https://github.com/cucumber/cucumber/wiki/Spoken-languages

Looks like, it will work

Please, try and provide feedback

**Comment by esthinri** [comment]
thanks
