### ISSUE TITLE
Error on command page open

### ISSUE THREAD

**Issue by esthinri** [strongqa/howitzer#272]
Howitzer Version:2.1.1
Driver and browser information: selenium_grid
Gem Versions: 2.5.1

#code

Given("I open Atlas Quantum page") do
  page open # Write code here that turns the phrase above into concrete actions
end

#error

  Scenario: Submit form empty                     # features/example.feature:3
    Given I open Atlas Quantum page               # features/step_definitions/common_steps.rb:7
      wrong number of arguments (given 0, expected 1..3) (ArgumentError)
      ./features/step_definitions/common_steps.rb:8:in `initialize'
      ./features/step_definitions/common_steps.rb:8:in `open'
      ./features/step_definitions/common_steps.rb:8:in `"I open Atlas Quantum page"'
      features/example.feature:4:in `Given I open Atlas Quantum page'
    And I click in Register button                # features/step_definitions/common_steps.rb:17
    When I submit Register form                   # features/step_definitions/common_steps.rb:22
    Then the result should be error on the screen # features/step_definitions/common_steps.rb:31
WARN: Screenshot could not be saved. `page.current_path` raised exception: #<Selenium::WebDriver::Error::UnknownError: unknown error: unrecognized Blink revision: 2e6edcfee630baa3775f37cb11796b1603a64360
  (Driver info: chromedriver=2.10.267518,platform=Linux 4.13.0-31-generic x86_64)>.

Failing Scenarios:
cucumber features/example.feature:3 # Scenario: Submit form empty

**Comment by romikoops** [comment]
```
Given I open Atlas Quantum page # features/step_definitions/common_steps.rb:7
wrong number of arguments (given 0, expected 1..3) (ArgumentError)
```

Without the code in that line, difficult to say what do you execute there

**Comment by esthinri** [comment]
this:
Given("I open Atlas Quantum page") do
**page open** 
end

**Comment by romikoops** [comment]
it will not work like that. You need to understand how it works and what do you write.

Use something like that (AtlasQuantumPage should present)

```ruby
Given("I open Atlas Quantum page") do
  AtlasQuantumPage.open
end

**Comment by esthinri** [comment]
thanks, exists some place where i can download the code or some tutorial i follow (not video)

the video in howitzer site its confuse, i try to follow but i dont have success

**Comment by Lec1k** [comment]
@esthinri 
https://github.com/strongqa/howitzer_example_cucumber cucumber example there.
http://docs.howitzer-framework.io/ documentation.
