### ISSUE TITLE
Add 'phantomjs' driver support for selenium ~> 3.8.0

### ISSUE THREAD

**Issue by zozivan** [strongqa/howitzer#274]
## Meta
Howitzer Version: 2.1.0

## Expected Behavior
There should be  `phantomjs` directory in `selenium/webdriver` directory

## Actual Behavior
There is no **phantomjs** support for selenium ~> 3.8.0
## Steps to reproduce
1. Install new project of howitzer 2.1.0
2. Create howitzer gemset.
3. Open `External libraries -> selenium-webdriver -> lib -> selenium -> webdriver`

**Comment by mikhaillopandia** [comment]
Selenium has officially stopped support of phantomjs:
```
PhantomJS:
  * Support is deprecated in favor of headless Chrome/Firefox or HTMLUnit.
    PhantomJS is no longer actively developed, and support will eventually
    be dropped.
```
https://github.com/SeleniumHQ/selenium/blob/7f66c20dde7a4e939927b678f585d0586f160ca6/rb/CHANGES#L79

So we are going to stop support of phantomjs in Howitzer as well in new release.


But if you want to run your tests in phantomjs, you may use selenium-webdriver version with phantomjs support, i.e. 3.7.0 and just need to add string
```
gem 'selenium-webdriver', '3.7.0'
```
in your `Gemfile` and run
```
bundle update selenium-webdriver
```
