### ISSUE TITLE
Multiple sessions don't work properly

### ISSUE THREAD

**Issue by nataliya-m** [strongqa/howitzer#282]
In the test we need to log in as 2 different users to the same app in parallel
`I open session_1 for user_1`
`I open session_2 for user_2`
We can implement this step in such way:
`Given /^I open (\w+) for (\w+)$/ do |session, user|`
`  Capybara.session_name = session.to_sym`
`  Capybara.using_session(session.to_sym) do`
`    LoginPage.open`
`    LoginPage.on { login(user) }`
`  end`
`end`
For user_1 everything is ok, but for user_2 there is a problem - howitzer seizes HTML from the session_1.
The problem related to capybara_scopes:
https://github.com/strongqa/howitzer/blob/ccce583ec7b07614cca365a97869a6c12050ff67/lib/howitzer/web/capybara_methods_proxy.rb#L60

**Comment by Lec1k** [comment]
We have following 'solution' in our project, add to boot.rb
```ruby
module Howitzer
  module Web
    class Page
      private

      def capybara_scopes
        return @_scopes = [Capybara.current_session] if @_scopes.blank?
        return @_scopes = [Capybara.current_session] unless @_scopes.include?(Capybara.current_session)
        @_scopes
      end
    end
  end
```

And `Capybara.session_name = session.to_sym` is enough, you don't need to use `using_session` after that

**Comment by nataliya-m** [comment]
doesn't work without `using_session` too

**Comment by romikoops** [comment]
It would be really nice do not depend on Capybara. My proposal:

```ruby
# Executing code in default session
HomePage.on do
  expect(title).to eq('Home Page')
end

# Executing code in another browser
Howitzer.session_name = 'browser2'
LoginPage.on do
  expect(title).to eq('Login Page')
end

# Switching back to main browser
Howitzer.session_name = 'default'

# In this approach we start first browser and later second browser. Both browsers are open to the end of the test suite
```

```ruby
# Executing code in default session
HomePage.on do
  expect(title).to eq('Home Page')
end

# Opening page in another browser
Howitzer.using_session('browser2') do
  LoginPage.on do
    expect(title).to eq('Login Page')
  end
end

# here browser 2 is already closed
```
