### ISSUE TITLE
Official Docker image?

### ISSUE THREAD

**Issue by DannyBen** [strongqa/howitzer#317]
Is there any chance of having an officially supported Docker image on DockerHub? 
One that comes with all the dependencies needed, ready to be executed?

With such [a long dependencies list](https://github.com/strongqa/howitzer#requirements), it seems like a classic case where Docker can make things much easier and portable. 

If not possible - even a `docker-compose.yml` stack would be great.

**Comment by romikoops** [comment]
@DannyBen yes, I was thinking about it as well this Monday. Thank you for posting this issue, we will add it to the backlog and work on it. ETA 1-2 weeks.

**Comment by romikoops** [comment]
@DannyBen we are still working on the Docker/Docker Compose feature, which will be generated by howitzer for new projects. In meantime, you could use this Dockerfile https://github.com/strongqa/howitzer_example_rspec/blob/creating_dockerfile/Dockerfile

**Comment by romikoops** [comment]
In the `master` branch. The official image is not planned to publish on DockerHub, probably be in future releases.
